# Artificial Neural Network Project - Alaa Sweed - 318462959

## 0) Importing the relevant libraries

In [183]:
import numpy as np
import pandas as pd
import tensorflow as tf

## 1) Data Preprocessing

### 1.1) Importing the dataset

In [184]:
# loading iris dataset from csv file format
# i provided dataset with low accuracy for testing (iris-data-with-lower-accuracy.csv) or use deafult one with  high accuracy (iris-data.csv)
irisDataSet = pd.read_csv('iris-data.csv')
# loading input values from dataset
X = irisDataSet.iloc[:, :-1].values
# loading output values from dataset
y = irisDataSet.iloc[:, -1].values

In [185]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [186]:
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

### 1.2) Encoding categorical data

#### 1.2.1) There is no need to encode the input columns because everything in numeric

#### 1.2.2) One-hot encoding the output column: class

In [187]:
from sklearn.preprocessing import OneHotEncoder
# we use one-hot encoding because it most efficent way to encode categorial labels from class to numeric that will be used by ann (to make it suitable for ANN models)
one_hot_encoder = OneHotEncoder()
y_encoded = one_hot_encoder.fit_transform(y.reshape(-1, 1)).toarray()

In [188]:
print(y_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

### 1.3) Splitting the dataset into training and test sets

In [189]:
from sklearn.model_selection import train_test_split
# we split randomly the data: 80% of data is used for training and 20% for testing 
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

### 1.4) Normalize the input data (X) to improve ANN performance (i prefered to use Standardization over normalization because it rescales data for any distribution, while normalization is for normally distributed data. so overall Standardization is better)

In [190]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## 2) Building the ANN

### 2.1) Initializing the ANN with the Input layer

In [191]:
# in input layer: input_shape must match number of inputs columns 
ann = tf.keras.models.Sequential([tf.keras.Input(shape=(X_train.shape[1],))])

### 2.2) Adding the first hidden layer

In [192]:
# first hidden layer uses ReLU activation function
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

### 2.3) Adding the second hidden layer

In [193]:
# second hidden layer also uses ReLU activation function
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

### 2.4) Adding the output layer (we use softmax for categorial output)

In [194]:
# output layer uses Softmax activation function for multi-class classification(number of units matches number of classes)
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

## 3) Training the ANN

### 3.1) Compiling the ANN

In [195]:
# we use "adam" optimizer and "categorical_crossentropy" loss function for multi-class classification
ann.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

### 3.2) Training the ANN on the Training set

In [196]:
ann.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 910us/step - accuracy: 0.3850 - loss: 1.0318
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.3636 - loss: 0.9952
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.2883 - loss: 0.9908
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step - accuracy: 0.4253 - loss: 0.9548
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 755us/step - accuracy: 0.6725 - loss: 0.9391
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.6982 - loss: 0.9008
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6543 - loss: 0.8878
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6974 - loss: 0.8645
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6664 - loss: 0.8509 
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6485 - loss: 0.8506
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6451 - loss: 0.8303 
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 714us/step - accuracy: 0.9807 - loss: 0.3022
Epoch 69/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.9435 - loss: 0.3639
Epoch 70/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step - accuracy: 0.9616 - loss: 0.3367
Epoch 71/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - accuracy: 0.9850 - loss: 0.2974
Epoch 72/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - accuracy: 0.9493 - loss: 0.3112
Epoch 73/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.9549 - loss: 0.3263
Epoch 74/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9847 - loss: 0.2913 
Epoch 75/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.9725 - loss: 0.2652
Epoch 76/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.9326 - loss: 0.3020
Epoch 77/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - accuracy: 0.9476 - loss: 0.2803
Epoch 78/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 756us/step - accuracy: 0.9646 - loss: 0.2608
Epoch 79/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 847

## 4) Making the predictions and evaluating the model

### 4.1) Predicting the Test set results

In [197]:
# to solve an warning i changed X_test to TensorFlow tensor then passing it to ANN's prediction function
X_test_tensor = tf.convert_to_tensor(X_test, dtype=tf.float32) 
# making predictions 
y_pred_probs = ann.predict(X_test_tensor)
# converting predicted probabilities to class labels
y_pred = np.argmax(y_pred_probs, axis=1)
# extracting actual class labels
y_actual_values = np.argmax(y_test, axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


In [198]:
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [199]:
print(y_actual_values)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


### 4.2) Evaluating the model by Making the Confusion Matrix and calculate statistical metrics

In [200]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
cm = confusion_matrix(y_actual_values, y_pred)
print("Confusion Matrix:")
print(cm)

accuracy = accuracy_score(y_actual_values, y_pred)
precision = precision_score(y_actual_values, y_pred, average='macro')
recall = recall_score(y_actual_values, y_pred, average='macro')
f1 = f1_score(y_actual_values, y_pred, average='macro')

print("Statistical Metrics:")
print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1-score: {f1}')

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Statistical Metrics:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0
